#! /bin/sh

#Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
picom &
polybar -r example &
# layout is changed with alt+shift and caps acts like ctrl
setxkbmap -layout "us,ru" -option "grp:ctrls_toggle,ctrl:nocaps,grp_led:caps"
nm-applet &

#Workspace
bspc monitor -d I II III IV V VI VII VIII IX X

#Other Stuff
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xwinwrap -ov -ni -fs -- mpv -wid WID --keepaspect=no --loop ~/Pictures/wallpapers/6vcr-sailers.gif &
